Repository codefordc/rfj_expungement, pull requests merged in 2019-09, with the labels that each got.

#8 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: community

#11 Adding issue templates
  .github/ISSUE_TEMPLATES/bug_report.md
  .github/ISSUE_TEMPLATES/feature_request.md
  .github/ISSUE_TEMPLATES/feedback_or_discussion.md
  .github/ISSUE_TEMPLATES/questions.md
Labels: community

#10 Add dependencies git hooks
  .eslintrc.yml
  package-lock.json
  package.json
Labels: enhancement

#17 State machine implementation
  .gitignore
  examples/using-state-machine.js
  libs/state-machines.js
  package-lock.json
  package.json
Labels: enhancement, help wanted

#27 initial slapdash drafting of datamodel
  datamodel.json
  datamodel.schema.json
Labels: help wanted
